version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t lol .
