version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run:
          name: wait for dind to be up
          command: sleep 600
      - run:
          name: Build docker image
          command: docker build -t lol .
